/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const VerifyEmailLazyRouteImport = createFileRoute('/verify-email')()
const RegisterLazyRouteImport = createFileRoute('/register')()
const LoginLazyRouteImport = createFileRoute('/login')()
const CheckEmailLazyRouteImport = createFileRoute('/check-email')()
const IndexLazyRouteImport = createFileRoute('/')()
const AdminProductsLazyRouteImport = createFileRoute('/admin/products')()
const AdminFlashSalesLazyRouteImport = createFileRoute('/admin/flash-sales')()
const AdminDashboardLazyRouteImport = createFileRoute('/admin/dashboard')()

const VerifyEmailLazyRoute = VerifyEmailLazyRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/verify-email.lazy').then((d) => d.Route))
const RegisterLazyRoute = RegisterLazyRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const CheckEmailLazyRoute = CheckEmailLazyRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/check-email.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AdminProductsLazyRoute = AdminProductsLazyRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin/products.lazy').then((d) => d.Route),
)
const AdminFlashSalesLazyRoute = AdminFlashSalesLazyRouteImport.update({
  id: '/admin/flash-sales',
  path: '/admin/flash-sales',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin/flash-sales.lazy').then((d) => d.Route),
)
const AdminDashboardLazyRoute = AdminDashboardLazyRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/admin/dashboard.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/check-email': typeof CheckEmailLazyRoute
  '/login': typeof LoginLazyRoute
  '/register': typeof RegisterLazyRoute
  '/verify-email': typeof VerifyEmailLazyRoute
  '/admin/dashboard': typeof AdminDashboardLazyRoute
  '/admin/flash-sales': typeof AdminFlashSalesLazyRoute
  '/admin/products': typeof AdminProductsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/check-email': typeof CheckEmailLazyRoute
  '/login': typeof LoginLazyRoute
  '/register': typeof RegisterLazyRoute
  '/verify-email': typeof VerifyEmailLazyRoute
  '/admin/dashboard': typeof AdminDashboardLazyRoute
  '/admin/flash-sales': typeof AdminFlashSalesLazyRoute
  '/admin/products': typeof AdminProductsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/check-email': typeof CheckEmailLazyRoute
  '/login': typeof LoginLazyRoute
  '/register': typeof RegisterLazyRoute
  '/verify-email': typeof VerifyEmailLazyRoute
  '/admin/dashboard': typeof AdminDashboardLazyRoute
  '/admin/flash-sales': typeof AdminFlashSalesLazyRoute
  '/admin/products': typeof AdminProductsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-email'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/admin/dashboard'
    | '/admin/flash-sales'
    | '/admin/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-email'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/admin/dashboard'
    | '/admin/flash-sales'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/check-email'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/admin/dashboard'
    | '/admin/flash-sales'
    | '/admin/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CheckEmailLazyRoute: typeof CheckEmailLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  RegisterLazyRoute: typeof RegisterLazyRoute
  VerifyEmailLazyRoute: typeof VerifyEmailLazyRoute
  AdminDashboardLazyRoute: typeof AdminDashboardLazyRoute
  AdminFlashSalesLazyRoute: typeof AdminFlashSalesLazyRoute
  AdminProductsLazyRoute: typeof AdminProductsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/flash-sales': {
      id: '/admin/flash-sales'
      path: '/admin/flash-sales'
      fullPath: '/admin/flash-sales'
      preLoaderRoute: typeof AdminFlashSalesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CheckEmailLazyRoute: CheckEmailLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  RegisterLazyRoute: RegisterLazyRoute,
  VerifyEmailLazyRoute: VerifyEmailLazyRoute,
  AdminDashboardLazyRoute: AdminDashboardLazyRoute,
  AdminFlashSalesLazyRoute: AdminFlashSalesLazyRoute,
  AdminProductsLazyRoute: AdminProductsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
